name: Build, Push Docker Image to Amazon ECR and Deploy with Terraform

on:
  push:
    branches:
      - feature/ecs  # Execute o workflow quando houver push na branch 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Checkout source code
        uses: actions/checkout@v2

      # Definir variáveis
      - name: Set up variables
        run: |
          IMAGE_REPO_NAME=ecs/image      # Nome do seu repositório ECR
          IMAGE_TAG=${{ github.sha }}       # Usar o SHA do commit como tag da imagem
          IMAGE_FULL_NAME=103911837471.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          echo "IMAGE_REPO_NAME=$IMAGE_REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_FULL_NAME=$IMAGE_FULL_NAME" >> $GITHUB_ENV

      # Login no Amazon ECR
      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 103911837471.dkr.ecr.us-east-1.amazonaws.com

      # Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

      # Tag da imagem Docker com o caminho completo do ECR
      - name: Tag Docker image
        run: |
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 103911837471.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      # Push da imagem Docker para o Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 103911837471.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      # Configurar credenciais AWS para Terraform
      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Configurar o Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      # Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # Aplicar o plano do Terraform com a nova imagem
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image_url=$IMAGE_FULL_NAME"
